fun will_throw
{
var exc = void
try {[ will_throw()]}
catch const e {
}

try {
     [async will_throw() ]
}
catch const e { exc->e}}var exc = void
try {[ will_throw() ]
}
catch const e {
 e
}
assert exc
with-0,-0,5,-0{}