fun will_throw
{try {
 [ will_throw()... ]
}
catch const e { e
}

try { [ will_throw()... ]
}
catch const e {}
0[0]
=1

try {}
catch const e {
} yield 18
}

var exc = void
try {[ will_throw()... ]
}
catch const e {
}
assert exc