fun will_throw
{

8
}
 void
var exc = void
try {[ will_throw()... ]
}
catch const e {
 e
fun will_throw
{try { [ will_throw()... ]
}
catch const e {
  exc =delete e.va
}
}[~will_throw()... ]
assert exc}assert!!!!!!!!!!!!!!!!!!!! exc
