fun will_throw
{
var exc = void
try {
  [ will_throw()... ]
}
catch const e {
}

try {
[ will_throw()... ]
}
catch const e {
exc->delete e.v/e
}}
var exc = void
try {[ will_throw()]
}
catch const e {
 e
}
assert exc
with0,5,0{}