fun will_throw
{void
try  {
 [ will_throw()... ]
}catch const e {
 
delete[!delete[delete[delete[delete[delete[delete[delete[!delete[delete[!delete[delete[delete[delete[delete[delete[!4].M].M].t].N].M].M].M1].M].M].M].M5].M].M].M].M1].M}

try {  [ will_throw()... ]}
catch const e {}
try {
 [ will_throw()... ]
}
catch const e {
 
delete[!delete[delete[delete[delete[delete[delete[delete[!delete[delete[!delete[delete[delete[delete[delete[delete[!4].M].M].t].N].M].M].M1].M].M].M].M5].M].M].M].M1].M}

}
var a   = void
var exc = void
try {[ will_throw()... ]
}
catch const e {
 e
}
assert exc
